### ISSUE TITLE
discrepancy between conda-forge linux64 repodata.json and the metadata of the packages

### ISSUE THREAD

**Issue by marcbernot** [conda-forge/conda-forge.github.io#1134]
I noticed a discrepancy between the dependencies data coming from `conda search --info` and the one present in the recipes of the packages.

For example:
`conda search --info libtiff` gives the dependency zstd >=1.4.4,<1.5.0.0a0 while libtiff-4.1.0-hc7e4089_6.tar.bz2/info/recipe/meta.yaml has the dependency zstd >=1.4.4,<1.4.5.0a0

This results in making possible the creation of a seemingly incoherent environment like this one (when using conda-forge) :

`conda create -n incoherent libtiff zstd`

where libtiff 4.1.0 hc7e4089_6 coexists with zstd 1.4.5.

This is not specific to libtiff, I have other examples.

I checked https://conda.anaconda.org/conda-forge/linux-64/repodata.json and it yields zstd >=1.4.4,<1.5.0.0a0 which I guess is logical given the output of `conda search --info`.
Do you know why is repodata.json not synced with the actual content of the packages/recipes?

**Comment by beckermr** [comment]
We patch the repodata of the packages in order to maintain the ecosystem. This is normal and expected. The only true source is the repodata.json. Everything else is out of date or wrong. In the example above, the pin on zstd was too tight given its ABI compatibility. We loosened the pin to ensure that more environments are solvable and to ease the amount of maintenance. 

I am going to close this issue, but if you have more questions, feel free to reopen!
