### ISSUE TITLE
Setuptools version ceilings?

### ISSUE THREAD

**Issue by jsignell** [conda-forge/conda-forge.github.io#1575]
After the release of setuptools 60.0.3 yesterday, all the Python 3.7 and 3.8 tests started failing on Dask. This is because the versions of pandas and numpy in those envs hadn't yet moved to using `packaging.version`. This is the error:

```python-traceback
py.test dask --runslow --cov=dask --cov-report=xml -n4 
ImportError while loading conftest '/home/runner/work/dask/dask/conftest.py'.
conftest.py:28: in <module>
    import pandas  # noqa: F401
/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/pandas/__init__.py:22: in <module>
    from pandas.compat.numpy import (
/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:10: in <module>
    _nlv = LooseVersion(_np_version)
/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/setuptools/_distutils/version.py:57: in __init__
    stacklevel=2,
E   DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
Error: Process completed with exit code 4.
```

It feels like this could be fixed on the conda-forge side, but I think the correct fix would be to update all the old recipes for all packages and explicitly add setuptools with a ceiling. But that seems impossible.

Here is the dask PR where I am setting a ceiling on setuptools for these older envs: https://github.com/dask/dask/pull/8509

**Comment by isuruf** [comment]
> But that seems impossible.

You can hotfix the package dependencies. See for eg: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/master/recipe/gen_patch_json.py#L990-L996

PRs welcome.

**Comment by jsignell** [comment]
Whoa! So that affects all packages?

**Comment by jakirkham** [comment]
Have issues been raised with those projects (NumPy, Pandas, etc.) to make the needed fixes?

**Comment by jakirkham** [comment]
cc @rgommers @jreback (for awareness)

**Comment by rgommers** [comment]
We know, our CI started failing so it's fixed in `main`. However, it is a deprecation warning from another project, so not really a reason to go do a new bug fix release. `setuptools` 60.0 broke a _ton_ of things. And will continue to do so. I think it'd be wise to pin to `setuptools<60.0` in conda-forge globally.

**Comment by jakirkham** [comment]
AIUI the Dask failure mentioned above is because Dask's CI turns all warnings into error. Sounds like NumPy was in a similar situation (please feel free to correct me if I'm missing something). Idk if Pandas has seen this yet (though turning warnings to errors would like to demonstrate the issue).

That said, it is not entirely clear to me based on this particular issue that conda-forge should be doing something. Setuptools has merely indicated this functionality will be going away in a future release, but it still remains there at present (just with a warning which is clearly effective given this conversation 🙂). IOW code using `Version` still works with the new Setuptools.

Normally if there is a big issue in something like Setuptools my notifications are blowing up about it. Though haven't seen anything like this (with the exception of this warning discussion). Admittedly I've just gotten back so I could be missing things 😅

What other things did Setuptools break? Also how would those things effect conda-forge?

**Comment by rgommers** [comment]
> What other things did Setuptools break? Also how would those things affect conda-forge?

They re-enabled their vendored copy of `distutils` in 60.0, with a significant amount of backwards incompatible changes. NumPy and SciPy CI broke in multiple places, and we've pinned to <60.0 versions everywhere. We're unlikely to ever upgrade to >=60.0. Scikit-learn has pinned to <60.0 as well in its `pyproject.toml` now. I'm sure many other projects have.

It's easy to miss in `environment.yml` because the `setuptools` dependency is implicit, it comes in with `python` (don't know why, that should probably be reverted in the future when more projects use other build systems).

**Comment by jakirkham** [comment]
Thought @conda-forge/core ?

**Comment by beckermr** [comment]
I am against a global pin right now. 

We have ~14k feedstocks and I see a mention of maybe ~5-10 on this thread. I am well aware of how significant these projects are in our community though. I also understand how disruptive the setuptools API changes are, especially for tolling this low in the stack. 

However, a global pin is using the equivalent of a wrecking ball when a hammer will suffice. As stuff breaks, upper bounds can be added or upstream repos can be adjusted. This is no different than a python migration, for example. 

I do think it'd be great for us to collect the common errors and their solutions related to this. We can add this info to our docs to help people with the transition.

**Comment by beckermr** [comment]
Given the pin <60, we may need to add an ABI migrations branch to the setuptools feedstock that has the latest version below 60. This will ensure our bot continues to update this version as it puts out pinning changes.

**Comment by beckermr** [comment]
If they ever split off and/or break pkg_resources, then we'll need to really do some work. Right now many projects depend on setuptools at run-time so they can use the pkg_resources module.

**Comment by jakirkham** [comment]
Generally agree Matt.

> However, a global pin is using the equivalent of a wrecking ball when a hammer will suffice. As stuff breaks, upper bounds can be added or upstream repos can be adjusted. This is no different than a python migration, for example.

Yeah understand that. Also there may be some packages that require a new version of `setuptools` as they need new features, bug fixes, etc. So we probably need to remain flexible at a global scale.

> Given the pin <60, we may need to add an ABI migrations branch to the setuptools feedstock that has the latest version below 60. This will ensure our bot continues to update this version as it puts out pinning changes.

That seems reasonable. Though I think that will just be for new Python versions (or variants). Setuptools doesn't link to anything and has few dependencies itself.

> If they ever split off and/or break pkg_resources, then we'll need to really do some work. Right now many projects depend on setuptools at run-time so they can use the pkg_resources module.

IIUC the goal there is to slowly obviate the need for `pkg_resources` with various additions to standard Python like [`importlib.metadata`]( https://docs.python.org/3/library/importlib.metadata.html ), [`importlib.resources`]( https://docs.python.org/3/library/importlib.html#module-importlib.resources ), etc. as well as corresponding `backports.*`. That way packages can move away from `pkg_resources`.

Not really expecting `pkg_resources` to disappear overnight, but wouldn't be surprised if we see more warnings like this one cropping up suggesting people move.

**Comment by jaimergp** [comment]
`pkg_resources` failed to find some entry points in a colab installation while `importlib_metadata` succeeded, for example. `setuptools` docs recommend moving away from it so I'm +1 here, more warnings and errors can be expected in the future...

**Comment by beckermr** [comment]
We should add a hint to smithy about this.

**Comment by jakirkham** [comment]
What hint do you have in mind?

**Comment by beckermr** [comment]
Ack I wrote that comment too fast. We can't hint on upstream sources.

**Comment by jakirkham** [comment]
True. Suppose we could hint for `setuptools` in `run`. Though agree this ultimately comes down to upstream making changes.

**Comment by jaimergp** [comment]
Have we ever thought about linting/hinting on the test results? We could check the contents of the solved test environment, in that case. I think `conda-build` would need to output both the normal stdout _and_ the JSON object, which right now is not possible iirc.

**Comment by jaimergp** [comment]
(conda plugins would be sooo useful here)

**Comment by beckermr** [comment]
The linter runs in our heroku server. Conda build is run in azure etc. So we'd need a secure way to report statuses back to github without putting keys into public forks etc. I think this is just too hard right now.
