### ISSUE TITLE
Improve About Dev Meetings under Readme

### ISSUE THREAD

**Issue by chicken-biryani** [conda-forge/conda-forge.github.io#1649]
### Where should the content be added?

Readme

### What should be added?

The current content about the dev meetings such as the template, hack md, meeting notes, etc can be made a little more compact and crisp in nature.

### Additional information

--

**Comment by chicken-biryani** [comment]
@beckermr @kathatherine I'd like to take this up.

**Comment by kathatherine** [comment]
@chicken-biryani The additions look good. However, I know the core group was hesitant to open up our meetings to everyone currently. Where did you find that calendar information?

**Comment by chicken-biryani** [comment]
Hi @kathatherine it's in the Readme.

**Comment by chicken-biryani** [comment]
I could comment the line that involves the link and remove the last line. In that manner we won't loose the link? Or remove the line all together?

**Comment by beckermr** [comment]
We've had the link there for a while, we just keep pretty quiet about it.

**Comment by kathatherine** [comment]
I think we should bring it up in the meeting before we merge this in and make sure that it's something we want to make more visible. @chicken-biryani, I have a few comments for your PR, in case we do decide to merge it in. Since our next conda-forge meeting isn't until April 6th, feel free to find another issue to work on. Thank you!
