### ISSUE TITLE
Improve documentation on using emulation & cross-compilation

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#1841]
While there are a few mentions of emulation & cross-compilation in various points in the docs (like [Configuring `conda-forge.yml`]( https://conda-forge.org/docs/maintainer/conda_forge_yml.html ) or [Apple Silicon builds]( https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds )), there doesn't appear to be (or at least basic searching doesn't uncover it) a step-by-step walkthrough of what things a maintainer needs to do to setup an emulated build or enable cross-compilation. Would be good to have this to help more users get started on their own with these options (particularly when native builds fall over).

**Comment by jakirkham** [comment]
Some things that would be good to cover:

* `build` / `host` difference (what goes where)
* Effect of `build` / `host` with cross-compilation
* When selectors are needed `build_platform != target_platform`
* When is `cross-python`
* Why is `meson-python` not also in `build` (only [in `host`]( https://github.com/conda-forge/scikit-image-feedstock/blob/4ecab237e05c3d0b70894f82a7d8b074ce842863/recipe/meta.yaml#L36 ))?
* Ditto [with `pythran`]( https://github.com/conda-forge/scikit-image-feedstock/blob/4ecab237e05c3d0b70894f82a7d8b074ce842863/recipe/meta.yaml#L38 )
* How is `PATH` affected by `host` & `build` (does this change priority; why are CLI tools still gotten from `build` if they are in both)
  * The [conda-build docs]( https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#host ) mention `host` overrides `build`:
  * >  The build prefix is activated before the host prefix so that the host prefix has priority over the build prefix.

cc @stefanv (who looked over my shoulder when writing this list 😉)

**Comment by ahesford** [comment]
There are a lot of nasties that come up when talking about cross-compilation, and they get even worse when you bring Python into the mix. A good general guidline for the difference between `build` and `host` dependencies is "if it needs to run during the build, it goes in the `build` dependencies; if it needs to be available on the final host, it goes in the `host` dependencies; if both are true, it belongs in both". That's what we tell people writing packages for Void Linux (although the nomenclature in Void is different).

Python injects several complexities:
1. Usually, the build process is controlled from Python itself, so a Python interpreter for the `build` platform is required.
2. CPython extensions might link against header files provided by other packages, like `numpy` or `pythran`, but those headers should be installed for the `host` platform and those headers used.
3. The Python interpreter for the `build` platform probably needs access to native packages to actually perform the installation (`setuptools`, `flit_core`, etc.); this set may or may not overlap with the set of runtime dependencies.
5. The package-building process in Python often does some dependency checking and fails if packages needed at build or run-time are not detectable.
6. Python package building often queries the `sysconfig` package and, when run on the `build` platform, this will return the wrong information. The `host` Python cannot (usually) be run directly, so the only way around this problem is to tell the `build` Python that it should read `sysconfig` data for the `host` platform.
7. The package building process may attempt to query Python packages for information, which will (sometimes incorrectly) return information about the `build` platform rather than the `host`.

Things like `crossenv` attempt to automate the workaround in (6); it may do more than that, for example, by making `host` packages discoverable to the `build` Python to solve the problem of (5). (I don't use `crossenv`, so I don't know specifically what it does.) In simple cases, (5) can be hacked around by setting `PYTHONPATH` to point to wherever the `host` packages are installed, but complex packages (like `numpy`) that ship CPython extensions may not even be importable if the extension objects for the `host` arch cannot be loaded by the `build` interpreter. Thus, it is often the case that Python packages required for the `host` platform must be installed for the `build` platform. Worse yet, patching or environment manipulation may be necessary to override or supersede whatever information the `build` packages return is used by the build process.

The `meson-python` package need only be specified for the `build` platform because it is used at build time, by the `build` system, and does not provide any platform-specific bits for linking that would demand a `host` dependency. `pythran` is a bit more of a complicated case; it needs to be in `build` dependencies because its `pythran` entrypoint is invoked to generate source files that will be compiled. However, I believe it should also be in `host` dependencies because those source files almost certainly link to Pythran headers (they definitely do with `scikit-image`) and those headers should be the `host` headers. It may be the case that Pythran headers are architecture-independent, in which case the difference is moot; however, this should not be relied upon. If a future release of Pythran injects some architecture dependency, packages that only provide `build` versions of `pythran` could break in subtle and hard-to-detect ways!

The `$PATH` should almost never include the `host` root, because most of the executables therein will not properly function on the `build` platform. If it belongs in `$PATH`, it belongs in `build` dependencies!

**Comment by jaimergp** [comment]
> * The [conda-build docs](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#host) mention `host` overrides `build`:
> * > The build prefix is activated before the host prefix so that the host prefix has priority over the build prefix.

@jakirkham - I don't think this is accurate. Check this function in conda-build: https://github.com/conda/conda-build/blob/835820623dae74308ae12b8e06571720add3dcca/conda_build/build.py#L2195-L2238

This is an excerpt from a local `build_env_setup.sh` file I had around:

```bash
...
export CONDA_BUILD_STATE="BUILD"
export PIP_NO_BUILD_ISOLATION="False"
export PIP_NO_DEPENDENCIES="True"
export PIP_IGNORE_INSTALLED="True"
export PIP_CACHE_DIR="/Users/jrodriguez/tmp/bld/conda_1672781570085/pip_cache"
export PIP_NO_INDEX="True"
eval "$('/Users/jrodriguez/.local/anaconda/bin/python' -m conda shell.bash hook)"
conda activate "/Users/jrodriguez/tmp/bld/conda_1672781570085/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold"
conda activate --stack "/Users/jrodriguez/tmp/bld/conda_1672781570085/_build_env"
```

**Comment by jakirkham** [comment]
It would be great to get these corrections included in the docs

**Comment by dlqqq** [comment]
@ahesford (cc @vlad0x00)

> if it needs to be available on the final host, it goes in the host dependencies

Wait, then are host requirements analogous to run requirements installed at build time? That is, are host requirements essentially considered to be "requirements for both building and running" a package?

I find that the current documentation doesn't provide a clear answer to what host requirements exactly are. Here is the first paragraph from the section on host requirements:

> This section was added in conda-build 3.0. It represents packages that need to be specific to the target platform when the target platform is not necessarily the same as the native build platform. For example, in order for a recipe to be "cross-capable", shared libraries requirements must be listed in the host section, rather than the build section, so that the shared libraries that get linked are ones for the target platform, rather than the native build platform. You should also include the base interpreter for packages that need one. In other words, a Python package would list python here and an R package would list mro-base or r-base.

I've narrowed down my confusion to a list of questions that can be answered un-ambiguously:

1. **How do host requirements behave in the package lifecycle?** For example, if a package `foo` declares a host requirement `bar`, what happens when `foo` is built or installed?
2. **How are host requirements different from run and build requirements?**
3. **What problems do host requirements _uniquely_ solve?** Or are they merely a shorthand for run and build requirements? Examples would be extremely helpful here.

Answering these questions here would help start the PR to improve the documentation and bring this issue to a close. It would also offer immediate benefit to users and contributors. Looking forward to what the community has to say here!
