### ISSUE TITLE
Auto expire PRs and issues on staged-recipes

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#193]
So we have a lot of PRs on staged-recipes. Not all of them are in a place where the proposer is actively working on them (we are all guilty 😉 ). My suggestion is that we put in place an automatic expiry of PRs if they have been inactive for 28 days. The automatic and consistent process of a bot doing this really simplifies the conversation, and there is absolutely no reason that a PR proposer couldn't just re-open the PR (that would be a success IMO).

I'm seriously considering setting this up as a service, but wanted to canvas whether it is just me who thinks about closing issues in this way is a good idea. 😉

**Comment by ChrisBarker-NOAA** [comment]
+1

CHB

Sent from my iPhone

On Jul 13, 2016, at 7:40 AM, Phil Elson <notifications@github.com> wrote:

So we have a lot of PRs on staged-recipes. Not all of them are in a place
where the proposer is actively working on them (we are all guilty 😉 ). My
suggestion is that we put in place an automatic expiry of PRs if they have
been inactive for 28 days. The automatic and consistent process of a bot
doing this really simplifies the conversation, and there is absolutely no
reason that a PR proposer couldn't just re-open the PR (that would be a
success IMO).

I'm seriously considering setting this up as a service, but wanted to
canvas whether it is just me who thinks about closing issues in this way is
a good idea. 😉

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/conda-forge.github.io/issues/193>, or mute
the thread
<https://github.com/notifications/unsubscribe/AA38YHZaHfOs0jsZZR0IoVe_kyuwUBBaks5qVNy-gaJpZM4JLX2D>
.

**Comment by jakirkham** [comment]
It's a reasonable idea. Though a normal user won't be able to re-open the PR. So, they will have to ping someone with higher privileges to do it.

**Comment by patricksnape** [comment]
Seems reasonable - if it's dead for 28 days pinging a maintainer is probably a good way to let us know we someone is still thinking about the PR.

**Comment by jakirkham** [comment]
Maybe something less aggressive like a bot that just pings the author. I can see too many ways this script goes wrong and I'm much more prepared for dealing with an overly noisy bot than one that closes things in an unintended way.

**Comment by jakirkham** [comment]
It seems like this has gone quiet and there is more recent discussion in CFEP PR ( https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/9 ). So am going to go ahead and close this out. Would be great to have more people chime in over there.
