### ISSUE TITLE
conda-forge: to what extent private companies can use its tools?

### ISSUE THREAD

**Issue by ubaldot** [conda-forge/conda-forge.github.io#2129]
### Your question:

So far I know that Anaconda's tools such as conda can be used by private companies under a paid license.
However, I learned that `miniforge` is a good free alternative that can also be used by private companies free of charge being BSD3-clause licensed as long as the company is compliant with the rest of the copyright notice. Is it correct?
What about [setup-miniforge](https://github.com/conda-forge/setup-miniforge) GitHub action? It is licensed MIT so I assume that private companies can freely use it as well. Correct?

**Comment by xhochy** [comment]
You can use `setup-miniforge` freely as long as you comply with the license. It's short, so you can check all the terms. 

The miniforge code itself is `BSD-3-Clause` licensed, but you must be aware that the installer bundles software with other licenses. If you want to be sure, you must check them all. But they are all licensed under FOSS licenses.

Otherwise, for packages, you need to check the license of every individual package.

Disclaimer: I'm neither a lawyer nor do I know what your use case is, so I cannot give you exact advice.

**Comment by ubaldot** [comment]
Thanks for your insight. I will check with some lawyer :)
