### ISSUE TITLE
What is my job?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [conda-forge/conda-forge.github.io#2177]
### Your question:

Once I upload, consider me dead.

Is that a fair expectation? I'm willing to do whatever for submitting, but once done, I don't want to be responsible for anything afterwards.

The [Maintainer role](https://conda-forge.org/docs/maintainer/adding_pkgs/#maintainer-role) docs say I should merge stuff from bots and answer questions. On former, the [maintaining packages](https://conda-forge.org/docs/maintainer/updating_pkgs/) docs say that submitted packages cannot be edited. So, if my goal is to make `conda install pkg==version` work, this is redundant? As for questions, again, immutability allows changes only for future releases.

While I'm up for occasional maintenance, my issue is with it being "required".

What happens if I refuse to merge bot PRs and answer questions?

**Comment by hmaarrfk** [comment]
> Once I upload, consider me dead.

The fact that you are asking here makes you very much "not dead"!!! 😄
This in my mind is not OK. But it seems that this isn't your intention. 

I consider the expectation  to be "occasional maintenance". Generally speaking, others tend to jump in and collaborate when you aren't able to maintain.

Hopefully the conda-forge tooling makes maintenance manageable for the packages you care about.

After all, for me, conda-forge (and Open Source Software) for me is a place where people can collaborate on common goals and gain feedback.

> What happens if I refuse to merge bot PRs and answer questions?

You are free to spend your time as you wish.
Eventually, if it takes too long, an other maintainer might join to help out.

**Comment by carterbox** [comment]
> On former, the [maintaining packages](https://conda-forge.org/docs/maintainer/updating_pkgs/) docs say that submitted packages cannot be edited. So, if my goal is to make conda install pkg==version work, this is redundant? As for questions, again, immutability allows changes only for future releases.

As package builders/distributors it is common to build a package multiple times even if the source code (upstream version) remains unchanged. Packages that aren't rebuilt periodically become uninstallable due to package incompatability with the rest of the channel.

> What happens if I refuse to merge bot PRs and answer questions?

Honestly, nothing. We have no enforcement mechanism for abandoned packages. If you're going to abandon a package, the least you can do is leave a note in an issue on the feedstock that you have no plans to maintain the feedstock and provide some way for someone who wants to take over the job to contact you to transfer the maintainership without getting the core team involved.

**Comment by mfansler** [comment]
Maybe an exceptional case, but for R packages, we have a team that maintains most feedstocks. We're generally open to accepting recipes that hand off the maintenance responsibilities to us (i.e., `conda-forge/r` is only maintainer).

**Comment by OverLordGoldDragon** [comment]
Thanks all, makes sense.
