### ISSUE TITLE
status page: version update improvements

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge.github.io#2289]
## items

- [x] The version update section of the status page is hard to read due to the items being highlited in white. See below
- [x] the version update listing would be better off using the full width of the screen
- [x] we should show the version for items listed as queued

## screenshots

<details/>
<img width="523" alt="Screenshot 2024-09-06 at 4 22 21 AM" src="https://github.com/user-attachments/assets/bf9dde68-69de-4e1c-b459-0fecaf16bee9">

<img width="505" alt="Screenshot 2024-09-06 at 4 22 27 AM" src="https://github.com/user-attachments/assets/b5037505-fcfb-4de0-ba90-dbd75ce516ff">
</details>

cc @jaimergp

**Comment by jaimergp** [comment]
cc @HaudinFlorence for visibility

**Comment by jaimergp** [comment]
Added https://github.com/conda-forge/conda-forge.github.io/pull/2294 for items (1) and (2). Item (3) will require changes in the bot because [the version itself is not included in the JSON payload.](https://github.com/regro/cf-graph-countyfair/blob/ef5b64010c676c2be02759e9db567c8df1faafc4/status/version_status.json#L958)

**Comment by jaimergp** [comment]
Added https://github.com/regro/cf-scripts/pull/3002 for (3)
