### ISSUE TITLE
Using conda-forge channel on Windows results in Qt error

### ISSUE THREAD

**Issue by dennissergeev** [conda-forge/conda-forge.github.io#257]
After I installed a package from conda-forge channel on a fresh Anaconda environment on Windows, I am not able to launch Spyder or Anaconda Navigator due to the following error:
`This application failed to start because it could not find or load the Qt platform plugin "windows".`

The package (iris) seemed to be installed correctly, and is imported successfully. I'm also able to use Jupyter Notebook. However, it would be great to solve that problem with Qt.

**Comment by ocefpaf** [comment]
@dennissergeev in cases like this it is best if you open the issue in the `Qt` [feedstock](https://github.com/conda-forge/qt-feedstock).

Note that `conda-forge`'s `Qt` is incompatible with `defaults` due to the `jpeg` library. `defaults` uses `8*` and `conda-forge` uses `9*`. I advice you to install everything in a environment with either `defaults` or `conda-forge` as higher on the priority list depending on what package you want there.

Maybe on Windows conda-forge won't work as we do not build `Qt` there due to CI limitations. In that case I invite you to show some support to https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/5 which aims to solve https://github.com/conda-forge/qt-feedstock/issues/5
