### ISSUE TITLE
conda-forge badge

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#258]
Kind of a nifty idea would be to have a conda-forge badge. The purpose is to advertise the package is on conda-forge ( also advertising conda-forge as well 😉 ). Also the badge would link to the feedstock. This way one can see the recipe, have links to Anaconda.org, the current builds, etc. Also perhaps the badge could display some info like version or similar. Though this isn't strictly required for the first pass.

**Comment by epruesse** [comment]
Since the badges generally query an API for some current data, adding something to e.g. shields.io to pull the anaconda cloud api seems the right way. A version badge could look like this e.g:

 [![shield](https://img.shields.io/badge/conda%7Cconda--forge-v1.0.0-blue.svg)]() 
 [![shield](https://img.shields.io/badge/conda%7Cbioconda-v1.0.0-blue.svg)]() 

The left side is generally not meant to be "advertising", but just indicates what is being shown. For version badges, that is often the package manager (`npm`, `gem`, `pypi`). `npm` uses `@` to indicate specific distribution channels, e.g. `npm@next`, but `conda@conda-forge` feels reversed to me. Hence the `|`. 

The associated link isn't part of the badge but of the markdown. The easiest would be to render the badge into the feedstock README.md, including the link to itself.

**Comment by epruesse** [comment]
See issue badges/shields#1000 and PR badges/shields#1001

**Comment by jakirkham** [comment]
Thanks for taking this one on @epruesse. Definitely a fan of shields.io. Would be great to have badges easily available there.

**Comment by jakirkham** [comment]
There are now shields badges available. Also PR ( https://github.com/conda-forge/conda-smithy/pull/583 ) will add them to the feedstocks Readmes (once ready).

**Comment by ctrueden** [comment]
@constantinpape If you go to https://shields.io/category/downloads and scroll to Conda and click the corresponding Downloads button, you can then enter `conda-forge` for the channel, plus your package name, and then "Copy Badge URL" to get the link.
