### ISSUE TITLE
Sfepy does not seem to be available

### ISSUE THREAD

**Issue by wd15** [conda-forge/conda-forge.github.io#303]
Sfepy is listed as a Conda-forge package, see https://conda-forge.github.io/feedstocks

However, it does not seem to be in the channel

    $ conda install -c conda-forge sfepy
    Fetching package metadata .........
    Solving package specifications: .

    PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
      - sfepy

    You can search for packages on anaconda.org with

        anaconda search -t conda sfepy

Other packages are available, such as sgp4, which install fine with

    $ conda install -c conda-forge sgp4

**Comment by isuruf** [comment]
Problem is this line, https://github.com/conda-forge/sfepy-feedstock/blob/master/recipe/meta.yaml#L16
Remove that and rerender the feedstock for the package to be built. Let us know if you need any more information.

**Comment by isuruf** [comment]
I just realized this is your first contribution and you may not know the process. From the recipe you submitted, a repo was created here, https://github.com/conda-forge/sfepy-feedstock. Since you were added as a maintainer, you have been given merge access to the repo. When the packages are built, they will be uploaded to https://anaconda.org/conda-forge/sfepy.

There was a problem in the recipe submitted. It skipped all builds and therefore no package was uploaded. To fix this, please fork the repo https://github.com/conda-forge/sfepy-feedstock and download it locally. Then remove the problematic line. Since this changes how the package is built you'll need to rerender. To do that run the following commands.
```
conda config --add channels conda-forge     # add conda-forge channel
conda install conda-smithy
conda smithy rerender                                   # run this from root of the local git repo.
```
Upload the changes to your fork and create a PR to  https://github.com/conda-forge/sfepy-feedstock and then let's see what happens.

**Comment by jakirkham** [comment]
Any luck @wd15 ? Or do you have more questions?

**Comment by wd15** [comment]
@jakirkham @isuruf I followed the instructions and opened a pull request:

https://github.com/conda-forge/sfepy-feedstock/pull/1

**Comment by jakirkham** [comment]
Appears to be available now. Going to close this out. Feel free to ping to reopen if there are still issues that have been overlooked.

**Comment by jakirkham** [comment]
Also thanks for helping out @isuruf. 👍
