### ISSUE TITLE
PyQt broken with ImportError: libicui18n.so.56: cannot open shared object file

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/conda-forge.github.io#326]
Yesterday, something broke with PyQt from conda-forge, I think due to an update in the icu library. When I import PyQt I now see:

```
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory
```

Here is a Travis log before the failure, and one just after the failure:

https://travis-ci.org/glue-viz/glue/jobs/197583476

https://travis-ci.org/glue-viz/glue/jobs/197712860

I'm opening an issue here because I'm not sure whether this is something that should be fixed with the icu or PyQt package.

**Comment by ocefpaf** [comment]
It is not broken. I am pinning everything to `icu 58.*` to improve compatibility with `defaults`.
But Travis-CI is awfully slow and most of the packages are still pending and that is cropping up everywhere because conda breaks pinning to get higher versions.

The workaround for now is to explicitly define a dependency on `icu 56.*` to get the older packages.
(Or wait until I finish the pinnings, which hopefully will happen this weekend.)

**Comment by astrofrog** [comment]
> conda breaks pinning to get higher versions

@ocefpaf - do you mean this is a conda bug? Has it been reported?

**Comment by ocefpaf** [comment]
> @ocefpaf - do you mean this is a conda bug? Has it been reported?

IMO it is a bug. It is known and treated like a feature. Unfortunately conda also breaks build numbers, which IMO is even worse. Lower build number should never be installed unless explicitly defined by the user since higher build number always brings fixes to the packages.

I think I will be able to finish the `icu 58.*` pinning today. Travis-CI seems to be running fine now.

**Comment by looooo** [comment]
maybe this list should be updated? https://github.com/conda-forge/conda-forge.github.io/blob/a144cdbbee17680147603493c99b8092c9069c89/scripts/pin_the_slow_way.py#L29-L59

**Comment by ocefpaf** [comment]
You have an old version there. It was already updated:

https://github.com/conda-forge/conda-forge.github.io/pull/311

Qt is in the channel now. I'll rebuild pyqt soon.
