### ISSUE TITLE
lmfit build fail on python 3.6 on appveyor

### ISSUE THREAD

**Issue by tritemio** [conda-forge/conda-forge.github.io#364]
Hi,

[lmfit-feedstock](https://github.com/conda-forge/lmfit-feedstock) build is failing on appveyor (win-x64) for Python 3.6 with the error:

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - lmfit 0.9.6 py36_0
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package
```

Does anyone has any pointer to what the cause can be?

See full log [here](https://ci.appveyor.com/project/conda-forge/lmfit-feedstock/build/1.0.21/job/dsiv2n8yhbsp988o#L401).

Thanks!

**Comment by ericdill** [comment]
You're probably getting that error because one of the dependencies doesn't exist on the win-64 platform. Looking at the dependencies of lmfit [here](https://github.com/conda-forge/lmfit-feedstock/blob/master/recipe/meta.yaml#L25-L29), all of them are common except for `emcee`. If you look at the files available for emcee [here](https://anaconda.org/conda-forge/emcee/files), you can see that there is no win-64/py36 package for emcee yet. In fact, it look like the windows build is failing for emcee on win-64 for py35 and py36, [here](https://github.com/conda-forge/emcee-feedstock). The "windows build" badge is showing a failed state. Digging into that failed state seems to suggest that the upload simply timed out. Also that feedstock is out of date. [I'll rerender it with conda smithy 2.2.2 and push up the changes](https://github.com/conda-forge/emcee-feedstock/pull/9). If that builds successfully, we can restart the lmfit build to pick up the emcee dependency and the py35 and py36 lmfit build should be fixed

**Comment by tritemio** [comment]
Thanks so much!

**Comment by ericdill** [comment]
Alright, the emcee build *should* be fixed. Let's hope that it builds on the merge. Status can be monitored here: https://ci.appveyor.com/project/conda-forge/emcee-feedstock/branch/master.

Next up is to restart the appveyor builds here: https://github.com/conda-forge/lmfit-feedstock/pull/8

And if lmfit/#8 works, then we should be good to go for a py36 lmfit build within the next couple of days. For whatever reason Appveyor has been very slow recently

**Comment by newville** [comment]
@ericdill Thanks! Much appreciated!

**Comment by tritemio** [comment]
lmfit-feedstock has now been built, closing.
