### ISSUE TITLE
Pinning gobject-introspection?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#436]
Seems we are pinning `gobject-introspection` in some cases and not others. Should it be pinned? If so to what? FWIW here is the [ABI report]( https://abi-laboratory.pro/tracker/timeline/gobject-introspection/ ).

**Comment by jakirkham** [comment]
cc @ocefpaf @pkgw @ccordoba12

**Comment by pkgw** [comment]
Looks like the ABI has been quite stable, which I think is something we can expect going forward since the GLib/Gtk+ folks are generally pretty careful about that stuff. In my personal packages I generally pin things "just in case" but if that adds to hassles on the conda-forge end, I don't think pinning is actually necessary.

**Comment by jakirkham** [comment]
Maybe just require `1.45.3` or greater as that is the last time a symbol was added?

**Comment by pkgw** [comment]
Sure, that seems like a fine policy.

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/conda-forge-pinning-feedstock #9](https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/9) via [**ZenHub**](https://www.zenhub.com/)
