### ISSUE TITLE
Support for libncurses6 in conda-forge

### ISSUE THREAD

**Issue by twrightsman** [conda-forge/conda-forge.github.io#474]
Dear @conda-forge/core team, conda-forge packages that depend on libncurses 5.9 are not installable in the latest version of conda (4.3.30) because libedit requires libncurses > 6.0. Can you consider relaxing the pinned ncurses version for conda-forge to allow libncurses6? See this pull request for more discussion: https://github.com/conda-forge/gnuplot-feedstock/pull/8

**Comment by jakirkham** [comment]
Updating to `ncurses` 6 is already being discussed in PR ( https://github.com/conda-forge/conda-forge.github.io/pull/461 ). So will close this out to consolidate the discussion.

Also `libedit` has been added to `conda-forge` pinned to `ncurses` 5.9. Linux packages are available and macOS packages should be available soon. This should workaround the updating issue.

Should note this underlying problem is an instance of issue ( https://github.com/conda/conda/issues/3968 ).
