### ISSUE TITLE
Mention webservices in conda_smithy page

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge.github.io#496]
https://conda-forge.org/docs/conda_smithy.html mentions nothing about the webservice

**Comment by dakshitathakkar** [comment]
Hi, @jakirkham. Is this issue open for changes?

**Comment by ssurbhi560** [comment]
Hi @isuruf,  :) 
The link you shared above doesn't work now (probably because it's an old issue and docs have changed a lot since then). But from what I have guessed you meant that there is no mention of web services in conda-forge docs under conda-smithy section. While looking through the docs, I found out that actually there is place ([here](https://conda-forge.org/docs/maintainer/infrastructure.html#web-services)) where web services are mentioned under conda-smithy
I just wanted ask you if this solved the issue, or you would like suggest something more for this?

**Comment by isuruf** [comment]
Yep, it's already there. Thanks @ssurbhi560.
