### ISSUE TITLE
Handling multiple versions

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#50]
Some packages like Python, NumPy, gcc, and others benefit by providing multiple version to ensure API/ABI compatibility. We should determine how to solve this and add the necessary logic for managing these cases. One thought was to have all versions in the same repo. Another was to have separate repos for each version (major, minor) patches and other lower versions would be an upgrade in that repo.

Related: https://github.com/conda-forge/conda-forge.github.io/issues/44

**Comment by sstirlin** [comment]
It seems to me there are a few options.  You can maintain this with 

(1) separate repos (i.e. cmake-3.3.2 and cmake-3.5.0) 
(2) separate branches in the same repo (with a naming convention)
(3) separate tags in the same repo (again with a naming convention)
(4) separate directories in the same repo (again with a naming convention).

I'm inclined to vote for (4) because I think it's the simplest and most easily managed.  That's what I did  in our project https://github.com/ActivisionGameScience/ags_conda_recipes (although there I dumped EVERYTHING together, but I like your idea of keeping different software in separate repos).

**Comment by jakirkham** [comment]
Just as FYI, 4 might be tricky as the idea of having multiple recipes in a feedstock is controversial. Technically it is feasible though. Here was a proposed implementation ( https://github.com/conda-forge/conda-smithy/pull/58 ).

I am guessing some mixture of 2 and 3 is on the table, but it will be good to get some more feedback from others.

Another possibly might be using more jinja templates to narrow down specifications for different version cases. Though we have to be ok with multiple builds and need some way of specifying how the version is set for each build and whether version builds should be iterated over or done in parallel matrix style builds.

On the NumPy point, we already do build multiple builds when there is ABI dependency, but we aren't using 1.8.x right now that could be raised. Here is [a recipe using the numpy ABI dependency]( https://github.com/conda-forge/mahotas-feedstock/blob/master/recipe/meta.yaml#L20 ) and [its packages]( https://anaconda.org/conda-forge/mahotas/files ).

**Comment by ocefpaf** [comment]
I am with @jakirkham here. I vote for (2), in fact that is already in play with the [gdal](https://github.com/conda-forge/gdal-feedstock) feedstock.

**Comment by jakirkham** [comment]
> Though we aren't using 1.8.x right now that could be raised.

It is worth keeping in mind that a 1.11.x release of NumPy is imminent.

**Comment by sstirlin** [comment]
Yeah, I don't really care about numpy 1.8.x per se, it's just an example of version complications and ABI compatibility problems that will arise in the future.  It's better to think about them now.  In truth I don't have a strong opinion - if you already have an idea that works then I say go forward with it.

I've been striving for the "distro" model.  Starting from a specific version of Anaconda, I build an ecosystem that is (more or less) the latest stable stuff that is compatible.  After 6 months I stop, fork, and begin again with a new version of Anaconda.

Presumably, with each passing generation the distro will become more full-featured.  Sometimes I debate with myself whether I should just go all the way down to libc and make the ecosystem totally self-contained.  For now I just always compile in RHEL 5 whenever possible since that has an old version of gcc (and gcc is forward ABI compatible).

Windows is nastier because a "platform" is not only determined by the version of Windows, but also depends on the version of Visual Studio that you build against.  Visual Studio doesn't guarantee any ABI compatibility whatsoever.

**Comment by grlee77** [comment]
Is there any more recent consensus on how multiple versions should be handled?  I recently ran across a case where I would like to make two versions of the C library NFFT available (3.2.4 which is the latest version compatible with the pyNFFT wrappers) as well as 3.3.1 which is the most recent release.

This [feedstock](https://github.com/conda-forge/nfft-feedstock) is currently at NFFT 3.2.4.  If I wanted to add a 3.3.1 build, would I just make a separate nfft3.3 branch in the feedstock to handle this?  

A simple alternative would be to just update the master branch to 3.3.1 and I assume the previous 3.2.4 builds would remain available via conda-forge.  I guess the drawback there would be if someone wanted to then go back and add Windows support or make some other change to the 3.2.4 recipe for use with pyNFFT it is no longer in its own separate branch.

**Comment by ocefpaf** [comment]
> Is there any more recent consensus on how multiple versions should be handled?

@grlee77 we can use branches for cases like that. We already have that working for [django](https://github.com/conda-forge/django-feedstock) and [gdal](https://github.com/conda-forge/gdal-feedstock).

> This [feedstock](https://github.com/conda-forge/nfft-feedstock) is currently at NFFT 3.2.4.  If I wanted to add a 3.3.1 build, would I just make a separate nfft3.3 branch in the feedstock to handle this?

Sure. However, I would recommend you to keep the old version in a branch, and let master be the latest.

> A simple alternative would be to just update the master branch to 3.3.1 and I assume the previous 3.2.4 builds would remain available via conda-forge.

Yep.

> I guess the drawback there would be if someone wanted to then go back and add Windows support or make some other change to the 3.2.4 recipe for use with pyNFFT it is no longer in its own separate branch.

In this case I would just update `nfft` and create the maintenance branch when/if the necessary. Bare in mind that you must pin the `pynfft` recipe to the working version of `nfft`. Otherwise conda will download the latest version.

**Comment by jakirkham** [comment]
The solution is multibranch feedstocks. Don't recall if there was anything else I was after. Closing as resolved.
