### ISSUE TITLE
Better document our environment variables

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-forge.github.io#651]
There are some env vars that affect building, rerendering, etc.  We should have a listing of these in the docs and what their allowed values are.

**Comment by ericdill** [comment]
@scopatz any thoughts on where in the docs these would live?

**Comment by scopatz** [comment]
I guess I would make a new page for them.

**Comment by viniciusdc** [comment]
@ericdill any thoughts on this?

**Comment by Martins-O-U** [comment]
@viniciusdc Outreachy Applicant here. Please share some more information on the environmental variables. I'd like to be assigned to work on documenting this.

**Comment by viniciusdc** [comment]
> @viniciusdc Outreachy Applicant here. Please share some more information on the environmental variables. I'd like to be assigned to work on documenting this.

HI @Martins-O-U  I think this issue was already been completed. As [this](https://conda-forge.org/docs/orga/guidelines.html?highlight=variables#intended-usage) toghether with [this](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#environment-variables-set-during-the-build-process) already cover the issue

**Comment by Martins-O-U** [comment]
Okay thanks @viniciusdc

**Comment by kathatherine** [comment]
@beckermr You think this can be closed?

**Comment by beckermr** [comment]
Yes I think so.
