### ISSUE TITLE
Upgrade to 4 total concurrent appveyor jobs until end of compiler migration

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-forge.github.io#657]
@conda-forge/core 

This PR falls under "all other voting items", please vote and/or comment on this PR. This PR needs 50% of core to vote yea to pass. To vote please leave Approve (yea) or Request Changes (nay) reviews. If you would like changes to the current language please leave a comment or push to this branch. This vote will end on 2018/10/23.

This aims to spend some of our financial resources on purchasing 2 more (for a total of 4) concurrent Appveyor jobs until the end of the compiler migration.  This is expected to cost $50 / month. @scopatz will pay and be reimbursed by Numfocus.

**Comment by CJ-Wright** [comment]
I guess we need a governance doc variant for issues (since review votes don't exist)? Although I would actually prefer this in a PR into a document which is a running tally of proposals (or a folder of proposals) since that allows us to track what is going on in a central place which is easy to find.

**Comment by scopatz** [comment]
OK! This passes! I'll go purchase the appveyor now.

**Comment by mwcraig** [comment]
Thanks, @scopatz!
