### ISSUE TITLE
document migrators

### ISSUE THREAD

**Issue by croth1** [conda-forge/conda-forge.github.io#737]
It may make sense to put a section on migrators in the documentation.

**Comment by CJ-Wright** [comment]
Feel free to take/link to https://regro.github.io/cf-scripts/ Please let me know if chunks are missing

**Comment by xhochy** [comment]
After going through this, I wondering how it is determined for which packages a migrator has to be run and which one already was fulfilled.

**Comment by croth1** [comment]
I agree that this information would be very useful. To my current understanding it depends on the depth of the dependency tree, maybe also how urgent it has to be spread through CF.

**Comment by CJ-Wright** [comment]
Which packages have been done is determined by the status of the bot's PR into that feedstock. If the PR is closed/merged then the bot assumes that everything is ok and can move on to its children.

**Comment by croth1** [comment]
Oh maybe I misunderstood the question: mine is a bit different then: How to decide whether a pin advancement has to go through a migrator and which can be done without.

**Comment by CJ-Wright** [comment]
Ah, we usually use https://abi-laboratory.pro/ or some other ABI tracker to tell us if there are incompatibilities.

**Comment by CJ-Wright** [comment]
To some extent all the ABI breaking changes are urgent, since new packages (or packages which rerender) will potentially get bad envs, as the ABIs aren't compatible. This is why CFEP9 is in the works to swap the order of migration and pin change so that the new pins are built against before they are given out for general consumption.
