### ISSUE TITLE
44 new feedstocks ...

### ISSUE THREAD

**Issue by anguslees** [conda-forge/conda-forge.github.io#8]
I can generate pull-requests or whatever makes your life easier, but I'd like to move all my python conda packages into conda-forge.

They're currently uploaded to https://anaconda.org/gus and conda recipe is in https://github.com/anguslees/conda-*

Assuming that's within the vision of conda-forge, let me know what I can do to make this easier for you.

Package list (basically openstack nova/novaclient and its dependencies):
amqp
anyjson
cliff
cmd2
debtcollector
extras
iso8601
jsonpatch
jsonpointer
kombu
librabbitmq
linecache2
monotonic
netaddr
netifaces
nova
oslo.concurrency
oslo.db
oslo.log
oslo.messaging
oslo.middleware
oslo.rootwrap
paste
posix_ipc
prettytable
python-cinderclient
python-glanceclient
python-mimeparse
python-neutronclient
python-novaclient
retrying
rfc3986
routes
simplejson
sqlalchemy-migrate
tempita
testresources
testscenarios
testtools
traceback2
unittest2
warlock
websockify
wrapt

**Comment by ChrisBarker-NOAA** [comment]
not sure the best procedure -- as each one goes in its own repo (that is the plan, yes?), then that would be a lot of pul requests. 

But let's figure out a way -- this is the whole idea!

**Comment by anguslees** [comment]
So I can generate the right file-tree easily enough - I think the only difficult step is actually getting that into the right github repo.  Do you want to A) create a bunch of empty repos first, and then I generate PRs against them, or B) I create the repos elsewhere first and then you create+clone them across to conda-forge?

**Comment by ChrisBarker-NOAA** [comment]
I say create them right in the organization -- why create the extra overhead?

But I think Phil is on Holiday for a couple weeks -- and this is really his Baby, and I
I'm not sure who has permission ot give you permission to create the repos.

-Chris

**Comment by ChrisBarker-NOAA** [comment]
Actually -- I do know -- there are a few people listed as owners -- @mwcraig -- do you think we should move on this?

**Comment by mwcraig** [comment]
@anguslees -- wow, awesome! Just to be clear, a bunch of the infrastructure here is still not working.

To answer the question @ChrisBarker-NOAA raised, this is where the one-repo, one-recipe model breaks down, I think, because it would mean giving everyone who contributes a feedstock repo full owner rights.

I wonder if @pelson had a solution in mind for this.

In the short term, @anguslees, are there one or two we can try starting with, ideally ones without dependencies? 

The idea with conda-smithy was that it would auto-register projects with the CI services, but that isn't working yet, so getting all 44 packages set up will take a while (3 CI services per package).

But to really try this out we need to get one or two going!

**Comment by anguslees** [comment]
Yeah, I understand this is very new - so I'm happy to fumble through this
with you as and when we work it out.

Also to be clear, I actually don't care whether I remain an owner of these
repositories or not - it just seemed silly to let a bunch of work go
un-shared and eventually bitrot when something like conda-forge existed ;-)

I'll leave it up to you to tell me what I should do next - when you're
ready.

 - Gus

**Comment by jakirkham** [comment]
Do you still need help on this @anguslees? There has been some serious improvements on the infrastructure since you opened this issue. If you want, you can open one PR with all of those recipes in it. If the CIs timeout, we might need to break it up a bit. When do you want to get started?

**Comment by pelson** [comment]
I think we can close this issue. conda-forge is properly open for business - we encourage everybody to submit conda recipes which you are prepared to maintain (to an extent) should issues with the recipe and associated build arise. In exactly the same way as normal OSS development, it is encouraged to submit many small PRs rather than one big one, as this will allow us to iterate quickly and "bank" (aka merge) the ones that have no issues.
