### ISSUE TITLE
migrations / version updates for globally pinned packages 

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge.github.io#850]
This issue is here to document the discussion in https://github.com/regro/cf-scripts/issues/581

Right now, the version update bot is proposing updates for globally pinned packages by making PRs on the feedstock directly. This is causing feedstocks to get inconsistent applications of the global pins. 

A few solutions were proposed. 

1. We could have the version update bot propose full migrations via CFEP-9. 

2. We could force all globally pinned versions to have their own branches in each feedstock. Then we can enable pinning migrations to migrate all branches of a feedstock. This would effectively backport pins. 

Note that this is not an either or type of thing. Enabling both of these things would create an effective matrix of builds that would support many interoperable versions of packages.

**Comment by beckermr** [comment]
@CJ-Wright @mariusvniekerk @isuruf for viz

**Comment by CJ-Wright** [comment]
Some brief, non-comprehensive, thoughts:
1. I'm not sure I like the coupling of these two things, what versions we have available for users to install and what version we guarantee compatibility with could be separate things. This is especially important for downstream maintainers which may be interested in pinning their own packages against more recent versions of binaries we built.
2. I think this is the more general solution, but will require *much* more infrastructural work, as we'll need to have something make version branches for all the packages we pin. Additionally this will require the bot to handle multiple branches (not hard, but needs to be implemented). Finally we need a way to eliminate branches, since we most likely don't want a PR explosion for old pins. The upshot of this is better bot support for branches, which could go some way to backporting versions for packages with a LTS model.

**Comment by beckermr** [comment]
Do we have a policy on supporting outdated global pins? It seems like we need one in order for 2 to not explode as you say. Right now our effective policy is bleeding edge or some existing build, but no backporting. 

Maybe instead of branches for each pinned package, we support the second to most recent global pinnings version that resulted in a change in the feedstocks build?

**Comment by CJ-Wright** [comment]
What do you mean exactly by support? The built packages are in the channel, you can access them, we just currently don't build new packages on top of those with older pins.

**Comment by beckermr** [comment]
Sorry I was not clear! Here is what I mean. Suppose I have a package `pkg` that depends on a pinned dependency `dep`. Then think through the following timeline.

1. I release v1 of `pkg` and it builds against v1 of `dep`
2. The global pinning for `dep` is bumped to v2 and v1 is rebuilt against v2 of `dep`. 

At this point, in the conda channels we have

- `pkg=1` w/ `dep=1`
- `pkg=1` w/ `dep=2`

3. Then I release v2 of `pkg` and it builds against v2 of `dep`.

So finally, we have 

- `pkg=1` w/ `dep=1`
- `pkg=1` w/ `dep=2`
- `pkg=2` w/ `dep=2`

Given this set fo packages above, I would say conda-forge supports automatic maintenance of only the latest build of a package with only the latest set of global pins. The old packages are around OFC, but we don't make a commitment to update old versions with new pins. This is exactly the point you made when saying we don't backport pins. 

My questions/suggestions above are basically:

1. Is the statement I made about supported automatic maintenance correct? (I think yes.)
2. Should we support backporting the next to most recent global pin (v1 of `dep` above) to the most recent build of any package (v2 of `pkg`)?

This limits the build matrix while potentially providing more interoperability between different versions of packages.

Does this all make sense or am I missing something?

**Comment by CJ-Wright** [comment]
Thank you for clarifying!
This makes more sense.
My concern is that this might explode the matrix quite a bit. Consider `root` which has many deps it links against. Does that mean that every pinned dep gets a pair of builds?

One approach would be to work similar to the [numpy python plan](https://numpy.org/neps/nep-0029-deprecation_policy.html), but for all pinned packages. This would create many builds, but would give us a more orderly depreciation process.

Note that a combination of most recent and second most recent pins may not be compatible.

**Comment by beckermr** [comment]
So what I mean is not each pin per package, but only the actual version in the conda-forge pinning feedstock. This version is done by **date** and gets bumped on a ~monthly basis. So we only support the last two dates of the entire global pinning file. This would ensure compatibility (assuming the global pinnings file is internally compatible.) It also eliminates huge build matrices.

**Comment by beckermr** [comment]
Here is the screen shot of the pinnings builds:

![Screen Shot 2019-10-04 at 11 00 17 AM](https://user-images.githubusercontent.com/5296416/66222206-39c1dd00-e696-11e9-870b-181ef614759d.png)

The cadence here might be a bit high. We could pick one per month, say the last one tagged in the previous month.

**Comment by CJ-Wright** [comment]
Ah ok, that could move us off certain pins quite rapidly, since the [cadence is a bit faster than once a month](https://github.com/conda-forge/conda-forge-pinning-feedstock/commits/master/recipe/conda_build_config.yaml)

How do you think this will interact with the migrations themselves?

**Comment by beckermr** [comment]
A migration is only moved into the global pinnings file once it is done. So I think we need three branches per feedstock

1. bleeding edge on master
2. last tagged monthly global pinnings files.
2. next to last tagged monthly global pinnings files.

We should just pick one of the global pinnings per month to keep for a while.

**Comment by CJ-Wright** [comment]
Hmm.
I would propose a slight change: maybe we should declare `n` numbers of LTS global pinnings which we will build against for `x` months in addition to the bleeding edge pinnings. I don't want to lock ourselves into any particular calendar cadence, since some pinnings may make more sense as LTS without regard for the date.

This would provide more stability for downstream consumers, as they will be able to know when a pinning will go out of date, rather than the current system which runs at the cadence of the upstream packages.
This will also provide more time for maintainers and source code developers to release code without instantaneously needing to address any incompatibilities. I see this as being akin to python 2.7 support, where people know that they need to move off python 2.7 but they still want to release code under that pin while they are transitioning their API/ABI compatibility. Currently if someone wants to push out a new version which uses a pinned package, if they don't support our current pin then they are out of luck.

@conda-forge/core thoughts?

This may need to be put up as a CFEP at some point (maybe CFEP-9a?), but I think feedback on the idea might be good before we crystallize it into a formal proposal.

**Comment by beckermr** [comment]
Yup. That idea is way better! It parallels with the "too big to fail packages" as well, I think.

**Comment by CJ-Wright** [comment]
@msarahan @soapy1

**Comment by beckermr** [comment]
I am closing this issue as most of the main ideas made it into CFEPs or are implemented now.
