### ISSUE TITLE
Push to regro-cf-autotick-bot PR

### ISSUE THREAD

**Issue by micknudsen** [conda-forge/conda-forge.github.io#894]
Issue: I am listed as maintained on a recipe and therefore receive review requests for PRs made by the `regro-cf-autotick-bot`. For example [this one](https://github.com/conda-forge/pomegranate-feedstock/pull/2). It needs a few changes, and the page instructs me to

> add more commits by pushing to the 0.11.1 branch on regro-cf-autotick-bot/pomegranate-feedstock.

However, I do not have permissions to push to this. I recently had the same issue, but I posted my issue in the wrong repository, and I think it (and the solution) has been deleted. I have not been able to find any documentation about how to push to these PRs.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by CJ-Wright** [comment]
I'm not certain what is going on here? Is your git repo setup properly? If so then you can push up your own PR based on the bot's and any modifications you need.

**Comment by micknudsen** [comment]
This is what is happening:

```
% hub clone regro-cf-autotick-bot/pomegranate-feedstock
% cd pomegranate-feedstock
% git checkout 0.11.1
(...)
% git status
On branch 0.11.1
Your branch is ahead of 'origin/0.11.1' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
% git push
fatal: remote error:
  You can't push to git://github.com/regro-cf-autotick-bot/pomegranate-feedstock.git
  Use https://github.com/regro-cf-autotick-bot/pomegranate-feedstock.git
```

As suggested, I have tried using `https` instead, but it still fails. Maybe I miss something completely obvious here, but does one really need to create a duplicate PR to fix a bot PR?

Thanks!

**Comment by jakirkham** [comment]
Sounds like your remotes are messed up.

**Comment by croth1** [comment]
As @jakirkham mentioned there's a typo in the remote address:

`git://github.com/regro-cf-autotick-bot/pomegranate-feedstock.git` -> `git@github.com:regro-cf-autotick-bot/pomegranate-feedstock.git`

**Comment by micknudsen** [comment]
Thanks! Cloning `git@github.com:regro-cf-autotick-bot/pomegranate-feedstock.git` instead works great.

**Comment by jakirkham** [comment]
Glad to hear it!

**Comment by bradbell** [comment]
I am listed as a maintainer for the xrst-feedstock; see  recipe-maintainers on
https://github.com/conda-forge/xrst-feedstock/blob/main/recipe/meta.yaml
I created the original staged-recipe pull request for this package.

The bot created the following pull request (which has errors)
https://github.com/conda-forge/xrst-feedstock/pull/1

I obtained the the bot version of the xrst feedstock using
```
git clone git@github.com:regro-cf-autotick-bot/xrst-feedstock.git
```
I then made and checked in my corrections locally on the 2025.0.3_ha0f041 branch (which the bot chose for its update).
When I tried to push my changes I got the following:
```
git push
ERROR: Sorry, but @regro-cf-autotick-bot has blocked access to SSH keys created by some third-party applications.
Your key was created before GitHub tracked keys created by applications, so we need your help.
...
```

Perhaps I do not have the proper permissions  or is something else wrong or changed since procedure above worked ?

**Comment by bradbell** [comment]
> Sounds like you have outdated SSH keys.
>
My github keys work for other purposes, so I do not think this is a problem.

> In any event can you please move this to a new issue on that feedstock and ping core
> 
Thanks for the suggestion, I will do that.

> Commenting on several year old closed issues like this is more likely to be missed

**Comment by bradbell** [comment]
@jakirkham 
You were correct that it was about my ssh keys. I think the bot was complaining because my keys were very old. I created a new github ssh key and that solved the problem for me. 

Thanks for your help !

P.S.
When I used google to search for he original error message I got this bug report, so perhaps my experience will help others.
